### ISSUE TITLE
Open files on `@extends`, `@include` not working

### ISSUE THREAD

**Issue by PaolaRuby** [haidubogdan/netbeans-php-blade-plugin#5]
Hi, thanks for the amazing work, i'm using Netbeans 12.5

When I use `@include` and then `[CTRL] + CLICK` nothing happens, even with right click and `Navigate` > `Go to declaration`
It's that a bug or need some configuration for getting work, file path(string value) shows underline like link, but no file opens

**Comment by haidubogdan** [comment]
Hi,
It's likely to be a bug, sometimes this can be caused by cached file info in the netbeans editor. 
To fix this manually try to change the targeted file (the path from the include) save and then undo  and save again. This will trigger a clear cache.
It's also possible for this to happened due to custom path configuration for blade views. At the moment it's developed just for the standard relative paths starting with **views**. For this I will have to develop a include view path option to the folder or make the path declaration search more permissive.

**Comment by PaolaRuby** [comment]
>It's also possible for this to happened due to custom path configuration for blade views

My view are on path: **resources/views**

>To fix this manually try to change the targeted file (the path from the include) save and then undo and save again.

It didn't work for me

**Comment by haidubogdan** [comment]
I've managed to reproduce the bug. I will study the issue.

**Comment by haidubogdan** [comment]
I've published a new release on https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-04032022.
the current version 1.0.0.2 . Hope this will fix the issue.

**Comment by PaolaRuby** [comment]
>To fix this manually try to change the targeted file (the path from the include) save and then undo and save again.
>the current version 1.0.0.2 . Hope this will fix the issue.

Still not working, also i note that only the two first files are shown on the autocomplete suggestion, but I have 10 files in the folder, when I continue writing the number of suggestions does not increase, and the expected file doesn't appear, like it doesn't exists

**Comment by haidubogdan** [comment]
Ah it's not enough ... I still need to work on it.

**Comment by PaolaRuby** [comment]
>I hope with this release is better : https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-04032022a

still suggestions fails, not all the files are shown
![image](https://user-images.githubusercontent.com/88460896/156803727-c88830c4-e467-4e39-915d-0fb5cf3a3f0d.png)
![image](https://user-images.githubusercontent.com/88460896/156803817-cd2cd952-5bcf-441f-ad93-8f7142b8ba48.png)
![image](https://user-images.githubusercontent.com/88460896/156803994-27aa6921-53f5-4ff3-a695-e228f3242c3c.png)
On those captures `_audit` and `_modal` are not shown


>To fix this manually try to change the targeted file (the path from the include) save and then undo and save again.

Also tried and didn't work
Links to files still doesn't open the files

**Comment by haidubogdan** [comment]
Just to check, are you referring to relative paths autocomplete?
- /layouts
--- default.blade.php
--- admin.blade.php
so inside admin.blade.php I should see the 'default' suggestion directly without using the full path 'layout.default'

Some laravel features might have escaped me. I saw now this very old commit
https://github.com/laravel/framework/pull/7215

**Comment by PaolaRuby** [comment]
My views are on path: **resources/views/folder/file.blade.php**, and my include looks like
```blade
@include('folder.file')
```
Also i have others on path: **resources/views/folder/subfolder/file.blade.php**, and my include looks like
```blade
@include('folder.subfolder.file')
```

- **resources**
- - **views**
- -  -  **folder**
- -  - -   **subfolder**
- -  - -  - file.blade.php
- -  - -   file.blade.php

**Comment by haidubogdan** [comment]
On my side it seems to works fine ... maybe I have some exceptions or untreated error cases which might block the indexing / declaration process of the plugin.

**Comment by PaolaRuby** [comment]
## 😔🥺😭😭😭
I give up, I already tried to uninstall and reinstall, delete the netbeans cache, I don't know how to make you replicate the bug if it works correctly on your side

- `[CTRL] + CLICK` / `Navigate` > `Go to declaration` doesn't work for me
- Path `Suggestions` doesn't show all the blade files in folders

**Comment by haidubogdan** [comment]
Sorry about that :( 
I will see how the indexing and code completion can be more permissive.
I've added a small update for declaration finder for backward file path matching in case the blade file is in a custom directory.
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-05032022a

**Comment by PaolaRuby** [comment]
## 😀😀

Amazing, yo fixed it, everything works now,

Thanks a lot, works like a charm

**Comment by PaolaRuby** [comment]
@haidubogdan after upgrade to [1.0.0.6](https://github.com/haidubogdan/netbeans-php-blade-plugin/commit/fb6b0ed1b22e6b3a1e839b581385ed143a991051) `CTRL + CLICK` stop working, did you change something about that? It is showing other not related blade files on other paths with other names

Look, there is only one file on that path, but `Go to declaration` shows many
![image](https://user-images.githubusercontent.com/79208489/157335328-2cb4cfc7-3f18-4826-9fec-6b35fca7ef23.png)


Path suggestions still works at least

**Comment by haidubogdan** [comment]
Except for fixing the parser errors warning when you use expressions in directives with path. I didn't change the flow.
Maybe there's a logic which is too permissive for the declaration path which I think I can remove.
It's allowing fragments of blade view names to be detected as declaration results.

**Comment by PaolaRuby** [comment]
Yes, seems like shows the firsts blade files always

**Comment by PaolaRuby** [comment]
> Yes, seems like shows the firsts blade files always
